
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

 http:
  base_url: https://home.philippkeil.xyz
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
